version: "3.8"
services:
  sub-store:
    image: xream/sub-store:latest
    container_name: sub-store
    restart: always
    volumes:
      - /data/homelab-stacks/sub-store/data:/opt/app/data
    environment:
      - SUB_STORE_FRONTEND_BACKEND_PATH=/Ku91677Gk7fHKlMQagFl
    ports:
      - 13003:3001
    stdin_open: true
    tty: true
